### ISSUE TITLE
The "visible" check box when adding discussion questions doesn't appear to actually change the visibility of the question

### ISSUE THREAD

**Issue by meagansiu** [maltyeva/mindimp-pg#50]

**Comment by maltyeva** [comment]
Changed this and now all the questions shown on the book page are those that are marked as visible. Since there may be questions which are not shown on the page, to access them, I added a link to all of the book's questions visible to the admins. 

Some things to note - questions are not visible by default. I edited the database to make very question on the site (all 654 of them) visible, but in the future, make sure to check the box when adding a question, since altering the db isn't super safe (we have a backup though)
