### ISSUE TITLE
Profile Completion gauge

### ISSUE THREAD

**Issue by ChasonMindImp** [maltyeva/mindimp-pg#68]
Like on social media sites, create a gauge to mark profile completion, so that students are more compelled to do so without us having to email and harangue them to do so.

**Comment by maltyeva** [comment]
Alright, so this is completed. I'm going to push it tonight, because there are some major changes to existing users which will lock them out if their profiles aren't completed. I also took care of making sure new users will be properly redirected. 

As of now, the profile completeness is measured with completing the bio, high school, skype id, and adding a photo. we can add more features if necessary.
