### ISSUE TITLE
Add Lexile Measure column in book list

### ISSUE THREAD

**Issue by jzthompson** [maltyeva/mindimp-pg#7]
I don't think students should see this, but as long as the book list is only for administrators, this info would be helpful.

**Comment by maltyeva** [comment]
Would you want to the students to see the booklists eventually? Even if they do it shouldn't be an issue, because we can make that column just be seen by the administrator. 

For the lexile measure, I tried looking it up, but I wanted to check, is it stored as a number or as a phrase? As in, would it need to be something like 660, or 660L?

**Comment by jzthompson** [comment]
I think that having a student-accessible version of the book database would be great too.

We could just make the Lexile measure a number - 660, for example.

**Comment by maltyeva** [comment]
Great, this is fixed! Will be deployed to heroku tonight.
