### ISSUE TITLE
Edit Response Option

### ISSUE THREAD

**Issue by ChasonMindImp** [maltyeva/mindimp-pg#86]
There is also no way to edit text in a comment if there is an error or issue.

**Comment by maltyeva** [comment]
A comment to an article or a comment to an assignment for a class?

**Comment by ChasonMindImp** [comment]
My comment on a student response. I hit submit and caught a typo, but I
couldn't go back and change it.

On Wed, Apr 15, 2015 at 3:03 PM, maltyeva <notifications@github.com> wrote:

> A comment to an article or a comment to an assignment for a class?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maltyeva/mindimp-pg/issues/86#issuecomment-93226305>.
>



-- 
Chason Dailey | 戴奇森
Program Manager and Advisor* | MindImp 思脉*
https://www.mindimp.com/
https://app.mindimp.com/

**Comment by maltyeva** [comment]
You should still be able to add a comment and edit it once you hit submit. Let me know if you can't replicate it on the site.

**Comment by jzthompson** [comment]
I still can't find a way to edit comments I made on student responses to article discussion questions.

**Comment by maltyeva** [comment]
So this may be a phrasing issue actually. Add comments will either add
comments or edit the comments.

The way that the system works, the student can make the initial changes to
a response - creating a 'new' response, which locks them in, in order to
make sure they don't make changes afterwards (tracking the edits in the DB
and versioning is a possibility, but it would place an unnecesary burden on
our database.

The way that it works, is that an admin can 'edit' the responses, by adding
fields with separate comments, which can then be edited as many times as
they'd like. Does that workflow make sense for the sorts of things
we'retrying to do? Let me know if anything should be altered!

**Comment by jzthompson** [comment]
Ah, okay, I see how to edit now. I guess it might be nice to change the phrasing to "Add/edit comment" just so there is no further confusion, but aside from that, the way you have this structured makes sense.

**Comment by maltyeva** [comment]
ok! changed the wording for this issue. 

This is a great example of something making sense to me from a programming perspective but not making sense to the end user, so please don't hesitate to keep asking about these things!
