### ISSUE TITLE
"My Courses" displays differently depending on where it is accessed from

### ISSUE THREAD

**Issue by jzthompson** [maltyeva/mindimp-pg#97]
If I enter the administrator portal and click on "My Courses", I can see both the English and American Literature I taught last academic term and the writing course I will teach next week. However, if I access "My Courses" from the student portal, or if I click on the "My Courses" link on the side bar, I can only see the literature course.

**Comment by MindImpMatt** [comment]
I am having this issue as well. Maybe this is why some students can't see their classes?

**Comment by maltyeva** [comment]
I double-checked and this should be fixed. Currently, the instructor portals will show the courses they are teaching, not ones they are enrolled in. Should the language be changed?

**Comment by MindImpMatt** [comment]
Ah I see. So the sidebar takes me to courses I'm enrolled in (as a student), but the admin portal link goes to the ones I am instructing. Is this the same then for the actual students on the site? If so, then I think the language should be fine (since they usually won't go through the Admin portal anyway).

**Comment by maltyeva** [comment]
OK, I formatted the page a little more so it should be less confusing!
